# These are supported funding model platforms

github: [coder123, dev234, softage215]
patreon:  patreon_coder123
open_collective: collective_coder123
ko_fi: ko_fi_coder123
tidelift: npm/react
community_bridge: codewithzen
liberapay: master322
issuehunt: dev234
otechie: operations345
lfx_crowdfunding: lfx_project
custom: ['liked.com', 'coding.com]
